# Generated by Django 5.0.6 on 2025-06-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodoques', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
